export { default as mypic } from "./Image/me1.jpg"
export { default as project1 } from "./Image/template2-home.webp"
export { default as netflix } from "./Image/netflix.jpg"
export { default as weather } from "./Image/Free-Weather-Mobile-App-Ui-Kit-Freebiefy-com.jpg"
export { default as DreamsHRMS } from "./Image/login-banner.png"
export { default as ReactCertificate } from "./Image/React Certificate.jpg"
export { default as QuessNumber } from "./Image/Quess-the-number.png"
export { default as GL_ReactJs } from "./Image/Vijay G -React-Js.jpg"
export { default as GL_JavaScript } from "./Image/Vijay G_JavaScript.jpg"
export { default as TreeJs } from "./assets/images/Three.js_Icon.svg.png"
export { default as VantaJs } from "./assets/images/diffusion.png"
export { default as ParticlesJs } from "./assets/images/nanotechnology (1).png"